# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: SWLOG
  params:
    description: "Seowon Choi's personal portfolio"

ko:
  languageCode: ko-kr
  contentDir: content/ko
  title: SWLOG
  params:
    description: 최서원의 개인 포트폴리오입니다.