# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: "CHOISEOWON'S PORTFOLIO"
  weight: 2
  params:
    description: "Seowon Choi's personal portfolio and AI projects."
    author: admin
    en:
  languageCode: en-us
  contentDir: content/en
  title: "CHOISEOWON'S PORTFOLIO"
  weight: 2
  params:
    description: "Seowon Choi's personal portfolio and AI projects."
    author: admin
  menu:
    main:
      - name: "Home"
        url: "/"
        weight: 10
      - name: "Resumé"
        url: "about/"
        weight: 20
      - name: "Contact"
        url: "contact/"
        weight: 30
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
ko:
  languageCode: ko
  contentDir: content/ko
  title: "최서원의 포트폴리오"
  weight: 1
  params:
    description: "전북대학교 컴퓨터공학부 최서원의 블로그입니다."
    author: admin
  menu:
    main:
      - name: "홈"
        url: "/"
        weight: 10

      - name: "소개"
        url: "about/"
        weight: 20

      - name: "프로젝트"
        url: "projects/"
        weight: 30

      - name: "활동"
        url: "activities/"
        weight: 40
        children:
          - name: "교내활동"
            url: "#oncampus"
            weight: 1
          - name: "교외활동"
            url: "#offcampus"
            weight: 2

      - name: "연락처"
        url: "contact/"
        weight: 50

     
    