# config/_default/params.yaml

marketing:
  seo:
    site_type: "Person"
    org_name: "최서원 포트폴리오 | 전북대학교 컴퓨터공학부"
    description: "전북대학교 컴퓨터공학부 최서원의 포트폴리오입니다."
    twitter: ""
    image: "uploads/swlog_logo.jpg"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
  verification:
    google: ""

appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L
  custom_css:
    - css/custom.css
